# Generated by Django 5.0.6 on 2024-05-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='cover',
        ),
    ]
