# Generated by Django 5.0.6 on 2024-05-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_image_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
